package af.asr.youtap.util;

public class TransactionData {

    /**
     * Describes the searched transaction type
     *
     * MERCHANTTRANSACTION
     */
    private String transactionType;

    /**
     * Last financial transaction’s date and time
     * YYYY MMDDhhmmss
     */
    private String TransactionDate;

    /**
     *  *Status code values 2 and 3 are displayed
     *  * and code values 1 and 4 are printed.
     *  * 0 – Successful
     *  * 1 – System error
     *  * 2 – Provisioning error
     *  * 3 – Input error
     *  * 4 – Declined
     *  * If the status is not successful the Message
     *  * field must be present in the response
     *  * message explaining the error.
     */
    private int status;

    /**
     * If the status is non-zero then this
     * parameter is sent and could be
     * displayed/printed on the client device.
     */
    private String searchTxnMessage;


    private String customerId;
    private String merchantId;
    /**
     * DMM – send money or Forex lookup
     * TOPUP – Topup
     * BILL – Bill payment
     * Merchant local transactions:
     * C2MP – (payment) money transfer from a
     * customer’s mobile money account to a
     * merchants account
     * C2MW – (withdrawal) money transfer from
     * a customer’s mobile money account to a
     * merchants account
     * C2MD – cash deposit from customer to
     * merchant
     * C2CW – transfer from a customer’s mobile
     * money account to the customers linked
     * bank account
     * C2CD – transfer from a customer’s linked
     * bank account to a customer’s mobile
     * money account
     * M2CT – Subscriber uses mobile money
     * account to purchase mobile phone airtime
     * top-up.
     * PINTOP– Subscriber uses mobile money
     * account to purchase mobile phone airtime
     * top-up voucher/PIN.
     * SNDMON – Subscriber uses mobile
     * money account to send money to other
     * subscribers or non-subscribers
     * CSHTOP – Subscriber uses Cash to send
     * mobile phone airtime to any mobile phone
     * user including himself/herself
     * CSHVOUT - Subscriber transfers a cash
     * amount to a non-mobile money subscriber
     * CSHVOUR – Non-mobile money wishes to
     * withdraw from a cash amount previously
     * transferred to him/her.
     * CP2MP – Prepaid card purchase
     * INTXF – Mei Tan
     * OUTTXF - Mei Tan
     * C2CD - Mei Tan
     */
    private String paymentType;

    /**
     * Transaction ID number generated by a
     * third party system the used to trace a
     * transaction.
     */
    private long paymentTrailId;

    


}
